[![Made by Mr.Sahraoui](https://img.shields.io/badge/Made%20by-Mr.Sahraoui-orange)](https://digitalpro.dev)
![NLP](https://img.shields.io/badge/NLP-TP%20%202-orange)

<table style="width: 100%;">
<tr>
<td style="width: 50%; text-align: right; vertical-align: middle;">
<img src="https://github.com/gitpizzanow/dummy-files/blob/main/tp1nlp.jpg?raw=true" width="150">
</td>
<td style="width: 50%; text-align: left; vertical-align: middle;">

##  (NLP)   | Text Manipulation &Fake News Classification
> [SERIE](https://tp1-nlp-ing4.netlify.app/)


* *Text cleaning*
* *Text normalization*
* *Text tokenization*


> [DATA](https://www.kaggle.com/datasets/emineyetm/fake-news-detection-datasets)

</td>
</tr>
</table>

In [6]:
import sys
!{sys.executable} -m pip install spacy
!{sys.executable} -m spacy download en_core_web_sm

Requirement already satisfied: spacy in c:\users\meriem-pc\anaconda3\lib\site-packages (3.8.14)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (0.9.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (2.1.3)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (2.10.3)
Requirement already satisfied: jinja2 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (72.1.0)
Requirement already satisfied: packaging>=20.0 in c:\users\meriem-pc\anaconda3\lib\site-packages (from spacy) (24.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\meriem-pc\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\meriem-pc\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\users\meriem-pc\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\meriem-pc\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\meriem-pc\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\meriem-pc\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\meriem-pc\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.4.26)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\meriem-pc\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: colorama in c:\users\meriem-pc\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click<9.0.0,>=7.1.1 in c:\users\meriem-pc\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.1.8)
Requirement already satisfied: cloudpathlib>=0.7.0 in c:\users\meriem-pc\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in c:\users\meriem-pc\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.6.0)
Requirement already satisfied: httpx>=0.24.0 in c:\users\meriem-pc\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in c:\users\meriem-pc\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.7.0)
Requirement already satisfied: httpcore==1.* in c:\users\meriem-pc\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\meriem-pc\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: wrapt in c:\users\meriem-pc\anaconda3\lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (1.17.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\meriem-pc\anaconda3\lib\site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\meriem-pc\anaconda3\lib\site-packages (from jinja2->spacy) (3.0.2)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     - -------------------------------------- 0.5/12.8 MB 2.7 MB/s eta 0:00:05
     --- ------------------------------------ 1.0/12.8 MB 2.3 MB/s eta 0:00:06
     ---- ----------------------------------- 1.3/12.8 MB 2.4 MB/s eta 0:00:05
     ----- ---------------------------------- 1.8/12.8 MB 2.3 MB/s eta 0:00:05
     ----- ---------------------------------- 1.8/12.8 MB 2.3 MB/s eta 0:00:05
     ------- -------------------------------- 2.4/12.8 MB 1.7 MB/s eta 0:00:06
     --------- ------------------------------ 2.9/12.8 MB 1.8 MB/s eta 0:00:06
     --------- ------------------------------ 3.1/12.8 MB 1.9 MB/s eta 0:00:06
     ----------- ---------------------------- 3.7/12.8 MB 1.9 MB/s eta 0:00:05
     ------------- -------------------------- 4.5/12.8 MB 2.0 MB/s eta 0:00:05
     --------------- ------------------------ 5.0/12.8 MB 2.1 MB/s eta 0:00:04
     ----------------- ---------------------- 5.5/12.8 MB 2.1 MB/s eta 0:00:04
     ------------------ --------------------- 5.8/12.8 MB 2.2 MB/s eta 0:00:04
     -------------------- ------------------- 6.6/12.8 MB 2.2 MB/s eta 0:00:03
     --------------------- ------------------ 6.8/12.8 MB 2.2 MB/s eta 0:00:03
     ---------------------- ----------------- 7.3/12.8 MB 2.2 MB/s eta 0:00:03
     ------------------------ --------------- 7.9/12.8 MB 2.2 MB/s eta 0:00:03
     --------------------------- ------------ 8.7/12.8 MB 2.2 MB/s eta 0:00:02
     ---------------------------- ----------- 9.2/12.8 MB 2.3 MB/s eta 0:00:02
     ------------------------------ --------- 9.7/12.8 MB 2.3 MB/s eta 0:00:02
     ------------------------------- -------- 10.2/12.8 MB 2.3 MB/s eta 0:00:02
     --------------------------------- ------ 10.7/12.8 MB 2.3 MB/s eta 0:00:01
     ----------------------------------- ---- 11.3/12.8 MB 2.3 MB/s eta 0:00:01
     ------------------------------------ --- 11.5/12.8 MB 2.3 MB/s eta 0:00:01
     ------------------------------------- -- 12.1/12.8 MB 2.3 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.8 MB 2.3 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 2.3 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 2.2 MB/s eta 0:00:00
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [66]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [67]:
import string

punctuations = list(string.punctuation) # Get all punctuation : !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [68]:
import pandas as pd

fake_df = pd.read_csv(r'C:\Users\meriem-pc\Downloads\archive (1)\News _dataset\Fake.csv')
true_df = pd.read_csv(r'C:\Users\meriem-pc\Downloads\archive (1)\News _dataset\True.csv')

In [69]:
len(fake_df)
len(true_df)

21417

In [70]:
fake_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [71]:
true_df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [72]:
fake_df['label'] = 0
true_df['label'] = 1

In [73]:
true_df_cols = true_df.columns
fake_df_cols = fake_df.columns

print (true_df_cols)
print (fake_df_cols)

Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')
Index(['title', 'text', 'subject', 'date', 'label'], dtype='object')

In [74]:
data = pd.concat([fake_df, true_df], ignore_index=True)
data = data.sample(frac=1, random_state=42).reset_index(drop=True) #shuffle the dataset

data.head()

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1

In [75]:
X = data['text'].tolist()[:50]
y = data['label'].tolist()[:50]

![ ](https://img.shields.io/badge/Text_normalization-red)

In [77]:
import sys
!{sys.executable} -m pip install num2words
from num2words import num2words

print(num2words(25))

Requirement already satisfied: num2words in c:\users\meriem-pc\anaconda3\lib\site-packages (0.5.14)
Requirement already satisfied: docopt>=0.6.2 in c:\users\meriem-pc\anaconda3\lib\site-packages (from num2words) (0.6.2)
twenty-five

![ ](https://img.shields.io/badge/Number_to_words_conversion%20%20-blue)

In [78]:
#comlete the from num2words import num2words
import re

def convert_numbers_to_words(text):
    def replace(match):
        return num2words(int(match.group()))
    return re.sub(r'\d+', replace, text)

In [79]:
print(convert_numbers_to_words("I have 2 apples and 15 bananas"))

I have two apples and fifteen bananas

![ ](https://img.shields.io/badge/drop_stop_words%20%20-blue)

In [80]:
def remove_stopwords(text):
    doc = nlp(text)
    result = []
    for token in doc:
        if not token.is_stop:
            result.append(token.text)
    return " ".join(result)

In [81]:
text = "This is a simple example to show how stopwords are removed"
print(remove_stopwords(text))

simple example stopwords removed

![ ](https://img.shields.io/badge/drop_punctuations%20%20-blue)

In [82]:
def remove_punctuation(text):
    result = ""
    for char in text:
        if char not in punctuations:
            result += char
    return result

In [83]:
text = "Hello!!! How are you??? I am fine :) #professeur sahrauoi "
print(remove_punctuation(text))

Hello How are you I am fine  professeur sahrauoi

![ ](https://img.shields.io/badge/Process%20%20-orange)

In [84]:
def process_text(text):
    text = text.lower()
    text = convert_numbers_to_words(text)
    text = remove_punctuation(text)
    text = remove_stopwords(text)
    return text

processed_X = []
for doc in X:
    processed_X.append(process_text(doc))

In [85]:
test = "I have 2 apples, and this is a simple test!!!"
print(process_text(test))

apples simple test

![ ](https://img.shields.io/badge/Vocabs%20%20-blue)

In [86]:
# vocab
vocab = []

for text in processed_X:
    words = text.split()
    for w in words:
        if w not in vocab:
            vocab.append(w)

# vectors
def text_to_vector(text, vocab):
    words = text.split()
    vector = [0] * len(vocab)
    
    for w in words:
        if w in vocab:
            index = vocab.index(w)
            vector[index] = 1
    
    return vector

Vectors = []
for text in processed_X:
    Vectors.append(text_to_vector(text, vocab))

In [87]:
print(len(vocab))
print(vocab[:20])

3485
['twentyonest', 'century', 'wire', 'says', 'ben', 'stein', 'reputable', 'professor', 'pepperdine', 'university', 'hollywood', 'fame', 'appearing', 'tv', 'shows', 'films', 'ferris', 'bueller', 's', 'day']

## BOW
>1-gram BOW

[![Naive Bayes](https://img.shields.io/badge/Naive_Bayes-classification-pink)](https://digitalpro.dev)

> Convert X docs to NumPy array

In [88]:
X_vectors = np.array(Vectors)
y_array = np.array(y)

In [89]:
import numpy as np

X_vectors = np.array(Vectors) #define your Vectors
y_array = np.array(y)

> Split into train/test

In [90]:
split_index = int(0.8 * len(X_vectors))

X_train = X_vectors[:split_index]
X_test = X_vectors[split_index:]

y_train = y_array[:split_index]
y_test = y_array[split_index:]

In [91]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_vectors, y_array, test_size=0.2, random_state=42, stratify=y_array
)

> Train Naive Bayes classifier

In [93]:
from sklearn.naive_bayes import BernoulliNB

model = BernoulliNB()
model.fit(X_train, y_train)

BernoulliNB()

In [94]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score, classification_report

nb = BernoulliNB()
nb.fit(X_train, y_train)    # Train

y_pred = nb.predict(X_test) # Predict

In [95]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8

> Evaluate

In [96]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.8
              precision    recall  f1-score   support

           0       1.00      0.60      0.75         5
           1       0.71      1.00      0.83         5

    accuracy                           0.80        10
   macro avg       0.86      0.80      0.79        10
weighted avg       0.86      0.80      0.79        10